language:
  - c
  - cpp
compiler:
  - gcc
  - clang

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake git scons libssl-dev
  - git submodule init
  - git submodule update
  - pushd udt4 && make && popd
  - pushd libconfig && touch lib/*.c && ./configure && make && popd
  - pushd tapcfg && ./buildall.sh && popd

script: mkdir build && cd build && cmake .. -DWITH_NVAGENT=no -DWITH_NVSWITCH=YES -DWITH_NVCTRLER=YES && make
